/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.cuc.convertidor;

import java.text.DecimalFormat;

/**
 *
 * @author David
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtR1 = new javax.swing.JTextField();
        R2 = new javax.swing.JTextField();
        R3 = new javax.swing.JTextField();
        R1 = new javax.swing.JTextField();
        RC = new javax.swing.JTextField();
        RB = new javax.swing.JTextField();
        txtRA = new javax.swing.JTextField();
        txtRB = new javax.swing.JTextField();
        RA = new javax.swing.JTextField();
        txtR2 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtR3 = new javax.swing.JTextField();
        txtRC = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        btnDeltaEstrella = new javax.swing.JButton();
        btnEstrellaDelta = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        ImagenDeltaEstrella = new javax.swing.JLabel();
        ImagenEstrellaDelta = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        pnlVerde = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setFocusTraversalPolicyProvider(true);
        setMinimumSize(new java.awt.Dimension(545, 480));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Rb");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 160, 20, -1));

        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Rc");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, -1, -1));

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Ra");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, -1, -1));

        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("R1");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, -1, -1));

        txtR1.setEditable(false);
        txtR1.setBackground(new java.awt.Color(153, 204, 255));
        txtR1.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtR1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtR1ActionPerformed(evt);
            }
        });
        getContentPane().add(txtR1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 40, 60, -1));

        R2.setBackground(new java.awt.Color(153, 204, 255));
        R2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R2ActionPerformed(evt);
            }
        });
        getContentPane().add(R2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 320, 30, -1));

        R3.setBackground(new java.awt.Color(153, 204, 255));
        R3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R3ActionPerformed(evt);
            }
        });
        getContentPane().add(R3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 410, 30, -1));

        R1.setBackground(new java.awt.Color(153, 204, 255));
        R1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R1ActionPerformed(evt);
            }
        });
        getContentPane().add(R1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, 30, -1));

        RC.setEditable(false);
        RC.setBackground(new java.awt.Color(204, 255, 204));
        getContentPane().add(RC, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 250, 60, -1));

        RB.setEditable(false);
        RB.setBackground(new java.awt.Color(204, 255, 204));
        getContentPane().add(RB, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 370, 50, -1));

        txtRA.setBackground(new java.awt.Color(204, 255, 204));
        txtRA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRAActionPerformed(evt);
            }
        });
        getContentPane().add(txtRA, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, 30, -1));

        txtRB.setBackground(new java.awt.Color(204, 255, 204));
        txtRB.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        getContentPane().add(txtRB, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 30, -1));

        RA.setEditable(false);
        RA.setBackground(new java.awt.Color(204, 255, 204));
        RA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RAActionPerformed(evt);
            }
        });
        getContentPane().add(RA, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 370, 60, -1));

        txtR2.setEditable(false);
        txtR2.setBackground(new java.awt.Color(153, 204, 255));
        txtR2.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtR2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtR2ActionPerformed(evt);
            }
        });
        getContentPane().add(txtR2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 40, 60, -1));

        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("R2");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 50, -1, -1));

        txtR3.setEditable(false);
        txtR3.setBackground(new java.awt.Color(153, 204, 255));
        txtR3.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtR3.setToolTipText("");
        txtR3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtR3ActionPerformed(evt);
            }
        });
        getContentPane().add(txtR3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 200, 60, -1));

        txtRC.setBackground(new java.awt.Color(204, 255, 204));
        txtRC.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtRC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRCActionPerformed(evt);
            }
        });
        getContentPane().add(txtRC, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 30, -1));

        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Rc");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 260, -1, -1));

        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("R2");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 330, -1, -1));

        btnDeltaEstrella.setText("Convertir");
        btnDeltaEstrella.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDeltaEstrella.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeltaEstrellaActionPerformed(evt);
            }
        });
        getContentPane().add(btnDeltaEstrella, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 180, -1, -1));

        btnEstrellaDelta.setText("Convertir");
        btnEstrellaDelta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEstrellaDelta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEstrellaDeltaActionPerformed(evt);
            }
        });
        getContentPane().add(btnEstrellaDelta, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 410, -1, -1));

        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("R1");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, -1, -1));

        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setText("R3");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 420, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setText("Conversion Estrellla - Delta");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 212, 38));

        jLabel18.setForeground(new java.awt.Color(0, 0, 0));
        jLabel18.setText("Rb");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 380, 20, -1));

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("R4");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 200, -1, -1));

        ImagenDeltaEstrella.setBackground(new java.awt.Color(255, 255, 255));
        ImagenDeltaEstrella.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/cuc/Imagenes/delta-estrella.jpg"))); // NOI18N
        getContentPane().add(ImagenDeltaEstrella, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        ImagenEstrellaDelta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/cuc/Imagenes/estrella-delta.jpg"))); // NOI18N
        getContentPane().add(ImagenEstrellaDelta, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 370, 170));

        jPanel6.setBackground(new java.awt.Color(204, 204, 255));
        jPanel6.setForeground(new java.awt.Color(255, 0, 102));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setText("Ra");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(386, Short.MAX_VALUE)
                .addComponent(jLabel17)
                .addGap(117, 117, 117))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(143, Short.MAX_VALUE)
                .addComponent(jLabel17)
                .addGap(69, 69, 69))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 530, 240));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(700, 480));
        jPanel1.setLayout(null);

        pnlVerde.setBackground(new java.awt.Color(204, 255, 204));
        pnlVerde.setForeground(new java.awt.Color(204, 204, 204));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setText("Conversion Delta-estrella");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(300, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 172, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlVerdeLayout = new javax.swing.GroupLayout(pnlVerde);
        pnlVerde.setLayout(pnlVerdeLayout);
        pnlVerdeLayout.setHorizontalGroup(
            pnlVerdeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlVerdeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlVerdeLayout.setVerticalGroup(
            pnlVerdeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlVerdeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(pnlVerde);
        pnlVerde.setBounds(10, 10, 530, 220);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 480));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 490, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 210, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 490, 210));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
  
    
    
    
    private void txtRCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRCActionPerformed

    private void R2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_R2ActionPerformed

    private void R3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_R3ActionPerformed

    private void R1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_R1ActionPerformed

    private void RAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RAActionPerformed

    private void txtR3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtR3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtR3ActionPerformed

    private void txtRAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRAActionPerformed

    private void btnDeltaEstrellaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeltaEstrellaActionPerformed
        // Delta a estrella
     double ResA = Double.parseDouble(txtRA.getText());
     double ResB = Double.parseDouble(txtRB.getText());
     double ResC = Double.parseDouble(txtRC.getText());
     
     double R11 ,R22,R33;
     
     R11 = (ResB * ResC)/(ResA + ResB + ResC);
     R22 = (ResA * ResC)/(ResA + ResB + ResC);
     R33 = (ResA * ResB)/(ResA + ResB + ResC);
     
     DecimalFormat Formato = new DecimalFormat("#.0000");
     
     txtR1.setText(String.valueOf(Formato.format(R11)));
     txtR2.setText(String.valueOf(Formato.format(R22)));
     txtR3.setText(String.valueOf(Formato.format(R33)));  
              
    }//GEN-LAST:event_btnDeltaEstrellaActionPerformed

    private void btnEstrellaDeltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstrellaDeltaActionPerformed
    // Estrella delta  
     double Res1 = Double.parseDouble(R1.getText());
     double Res2 = Double.parseDouble(R2.getText());
     double Res3 = Double.parseDouble(R3.getText());
     
     double RAA ,RBB,RCC;
     
     RAA = ((Res1*Res2)+(Res2*Res3)+(Res1*Res3))/Res1;
     RBB = ((Res1*Res2)+(Res2*Res3)+(Res1*Res3))/Res2;
     RCC = ((Res1*Res2)+(Res2*Res3)+(Res1*Res3))/Res3;
     
     
     
     DecimalFormat Formato = new DecimalFormat("#.0000");
     
     
     RA.setText(String.valueOf(Formato.format(RAA)));
     RB.setText(String.valueOf(Formato.format(RBB)));
     RC.setText(String.valueOf(Formato.format(RCC)));    
    }//GEN-LAST:event_btnEstrellaDeltaActionPerformed

    private void txtR2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtR2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtR2ActionPerformed

    private void txtR1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtR1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtR1ActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ImagenDeltaEstrella;
    private javax.swing.JLabel ImagenEstrellaDelta;
    private javax.swing.JTextField R1;
    private javax.swing.JTextField R2;
    private javax.swing.JTextField R3;
    private javax.swing.JTextField RA;
    private javax.swing.JTextField RB;
    private javax.swing.JTextField RC;
    private javax.swing.JButton btnDeltaEstrella;
    private javax.swing.JButton btnEstrellaDelta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel pnlVerde;
    private javax.swing.JTextField txtR1;
    private javax.swing.JTextField txtR2;
    private javax.swing.JTextField txtR3;
    private javax.swing.JTextField txtRA;
    private javax.swing.JTextField txtRB;
    private javax.swing.JTextField txtRC;
    // End of variables declaration//GEN-END:variables
}
